class Config:
    SECRET_KEY = "TS9He9WZmRZZF67a9mlz"
    RESCUE_GROUPS_USERNAME = "ann"
    RESCUE_GROUPS_PASSWORD = "r0cket"
    RESCUE_GROUPS_ACCOUNT_NUMBER = 8960
    TEMPLATE_FILE_ID = "1hjBCAQ2cJ8rWk3gIldge-tF_nWXyY9pgx-grRPJMtIA"
    TARGET_FOLDER_ID = "1P4bNgRcbTjAxvUI6Rgi5EKBc_taV83Jh"